#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/not_found.html
config="http {\n
	server {\n
		listen        80;\n
		server_name   localhost 127.0.0.1;\n
		location /redirect_me/ {\n
			return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n
		}\n
		error_page 404 /not_found.html;
    		location = not_found.html {
        		internal;
    		}
	}"
sed -i "s/http {/$config/" /etc/nginx/nginx.conf
service nginx start
