#!/usr/bin/env bash
# creates a file, and handles current process signals
terminator() {
	rm /var/run/myscript.pid
	exit
}
trap 'echo "I hate the kill command" && terminator' SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap 'terminator' SIGQUIT
echo "$$" > /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
